import { ContextMode, CurrencyCode, ModeConfig, MomOsState, GroceryDepartment } from './types';

export const CURRENCY_OPTIONS: { code: CurrencyCode; label: string; symbol: string }[] = [
  { code: 'ZAR', label: 'ZAR (R)', symbol: 'R' },
  { code: 'USD', label: 'USD ($)', symbol: '$' },
  { code: 'EUR', label: 'EUR (€)', symbol: '€' },
  { code: 'GBP', label: 'GBP (£)', symbol: '£' },
  { code: 'CAD', label: 'CAD ($)', symbol: 'CA$' },
  { code: 'AUD', label: 'AUD ($)', symbol: 'A$' },
];

export const MODE_CONFIGS: Record<ContextMode, ModeConfig> = {
  family: {
    id: 'family',
    title: 'Family & Kids Quick-Adds',
    shortTitle: 'Family & Kids',
    scheduleTitle: 'Family Schedule',
    iconName: 'Heart',
    defaultQuickAdds: [
      'School Drop-off',
      'Doctor Appointment',
      'Meal Prep Block',
      'Sports / Activity',
      'Bedtime Routine',
      'School Pickup',
    ],
    tagClass: 'tag-family',
    badgeBg: 'bg-rose-100/80 border-rose-300 text-rose-950',
    badgeText: 'text-rose-950 font-semibold',
    activeBtnBg: 'bg-stone-900 text-white border-stone-900 shadow-xs',
    cardBorder: 'border-stone-300',
    cardBg: 'bg-stone-50/70',
    accentText: 'text-stone-900 font-bold',
  },
  business: {
    id: 'business',
    title: 'Business Quick-Adds',
    shortTitle: 'Business & Clients',
    scheduleTitle: 'Business Pipeline',
    iconName: 'Briefcase',
    defaultQuickAdds: [
      'Client Call',
      'Work Sprint Block',
      'Send Invoice',
      'Order Fulfillment',
      'Proposal Review',
      'Inbox Zero Sprint',
    ],
    tagClass: 'tag-business',
    badgeBg: 'bg-slate-100 border-slate-300 text-slate-900',
    badgeText: 'text-slate-950 font-semibold',
    activeBtnBg: 'bg-slate-900 text-white border-slate-900 shadow-xs',
    cardBorder: 'border-slate-300',
    cardBg: 'bg-slate-50/60',
    accentText: 'text-slate-950 font-bold',
  },
  marketing: {
    id: 'marketing',
    title: 'Marketing Quick-Adds',
    shortTitle: 'Marketing & Content',
    scheduleTitle: 'Marketing Calendar',
    iconName: 'Megaphone',
    defaultQuickAdds: [
      'Write Newsletter',
      'Social Media Post',
      'Record Video',
      'Product Launch',
      'Engage on Stories',
      'Analytics Check',
    ],
    tagClass: 'tag-marketing',
    badgeBg: 'bg-amber-100/80 border-amber-300 text-amber-950',
    badgeText: 'text-amber-950 font-semibold',
    activeBtnBg: 'bg-amber-800 text-white border-amber-800 shadow-xs',
    cardBorder: 'border-amber-300',
    cardBg: 'bg-amber-50/60',
    accentText: 'text-amber-950 font-bold',
  },
  self: {
    id: 'self',
    title: 'Self & Admin Quick-Adds',
    shortTitle: 'Self & Admin',
    scheduleTitle: 'Self & Admin Schedule',
    iconName: 'Sparkles',
    defaultQuickAdds: [
      'Workout / Walk',
      'Admin & Invoicing',
      'Quiet Time / Read',
      'Grocery Run',
      'Hydrate & Stretch',
      'Weekly Review',
    ],
    tagClass: 'tag-self',
    badgeBg: 'bg-indigo-100/80 border-indigo-300 text-indigo-950',
    badgeText: 'text-indigo-950 font-semibold',
    activeBtnBg: 'bg-indigo-900 text-white border-indigo-900 shadow-xs',
    cardBorder: 'border-indigo-300',
    cardBg: 'bg-indigo-50/60',
    accentText: 'text-indigo-950 font-bold',
  },
};

export const getTodayDateString = (): string => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const DEFAULT_KID_TAGS = [ 'Family / All'];

export const ASSIGNEE_OPTIONS = ['Mom', 'Dad', 'Carers', 'Aunt & Uncle', 'Grandparent'];
export const SOLOPRENEUR_ASSIGNEE_OPTIONS = ['Primary', 'Contractor', 'Virtual Assistant', 'Client'];

export const DURATION_OPTIONS = ['5 mins', '15 mins', '30 mins', '45 mins', '1 hour', '2 hours'];
export const DURATION_PRESETS = DURATION_OPTIONS;

export const RECURRENCE_OPTIONS = [
  { value: 'none', label: 'Does not repeat' },
  { value: 'daily', label: 'Daily (Every day)' },
  { value: 'weekly', label: 'Weekly (Specific day)' },
  { value: 'monthly', label: 'Monthly (Day of month)' },
];

export const DELEGATION_LABELS: Record<string, string> = {
  myself: '👤 Myself',
  needs_partner: '🤝 Needs Partner',
  delegated_partner: '➡️ Delegated to Partner',
};

export const EXPENSE_SUB_CATEGORIES = [
  'School Supplies',
  'Extracurriculars',
  'Medical & Pharmacy',
  'Clothing & Shoes',
  'Snacks & Lunch',
  'Childcare / Babysitting',
  'Software & Apps',
  'Client Services',
];
export const EXPENSE_SUBCATEGORIES = EXPENSE_SUB_CATEGORIES;

export const SOLOPRENEUR_EXPENSE_SUBCATEGORIES = [
  'Software & Apps',
  'Client Services',
  'Office & Equipment',
  'Marketing & Ads',
  'Meals & Travel',
  'Professional Services',
  'Personal & Health',
  'Utilities & Subscriptions',
];

export const REIMBURSEMENT_LABELS: Record<string, string> = {
  none: 'Personal',
  pending_split: '⏳ Split Pending',
  reimbursed: '✅ Split Reimbursed',
  claimable: '💼 Tax Write-off',
};

export const CONTACT_CATEGORIES: { id: string; label: string; icon: string; color: string }[] = [
  { id: 'all', label: 'All Contacts', icon: 'Users', color: 'bg-stone-100 text-stone-700' },
  { id: 'emergency', label: '🚨 Emergency & ICE', icon: 'ShieldAlert', color: 'bg-rose-100 text-rose-800' },
  { id: 'family', label: '❤️ Family & Home', icon: 'Heart', color: 'bg-pink-100 text-pink-800' },
  { id: 'medical', label: '🩺 Medical & Doctors', icon: 'Stethoscope', color: 'bg-emerald-100 text-emerald-800' },
  { id: 'school', label: '🎒 School & Childcare', icon: 'GraduationCap', color: 'bg-amber-100 text-amber-800' },
  { id: 'carer', label: '🧸 Babysitters & Carers', icon: 'Baby', color: 'bg-purple-100 text-purple-800' },
  { id: 'service', label: '🔧 Home Services & Repair', icon: 'Wrench', color: 'bg-blue-100 text-blue-800' },
  { id: 'business', label: '💼 Work & Clients', icon: 'Briefcase', color: 'bg-indigo-100 text-indigo-800' },
];

export const GROCERY_DEPARTMENTS: GroceryDepartment[] = [
  'Produce',
  'Dairy & Refrigerated',
  'Meat & Seafood',
  'Pantry & Dry Goods',
  'Bakery & Snacks',
  'Other',
];

export const POPULAR_RECIPE_TAGS = [
  'Kid-Friendly',
  'Quick 20-Min',
  'Meal Prep Batch',
  'One-Pot / Sheet Pan',
  'Slow Cooker',
  'Gluten-Free',
  'Comfort Food',
  'Healthy & Fresh',
];

export const INITIAL_STATE: MomOsState = {
  customQuickAdds: {
    family: [],
    business: [],
    marketing: [],
    self: [],
  },
  kidTags: DEFAULT_KID_TAGS,
  contacts: [
    {
      id: 401,
      name: 'Dr. Sarah Jenkins, MD',
      category: 'medical',
      relationship: 'Pediatrician',
      mobile: '+1 (555) 382-9901',
      landline: '+1 (555) 382-9900',
      email: 'nurses@oakridgepediatrics.com',
      address: '742 Evergreen Terrace, Suite 300, Springfield',
      notes: 'Office open Mon-Fri 8am-5pm. Call after-hours triage line for urgent fevers.',
      isEmergencyContact: true,
      kidTag: 'Family / All',
    },
    {
      id: 402,
      name: 'Oakridge Elementary Front Desk',
      category: 'school',
      relationship: 'Principal & Attendance Office',
      mobile: '+1 (555) 492-1100',
      landline: '+1 (555) 492-1101',
      email: 'attendance@oakridgek12.org',
      address: '120 School House Lane, Springfield',
      notes: 'Mrs. Vance is Leo’s 2nd Grade teacher (Room 14). Notify before 1:30 PM for bus changes.',
      isEmergencyContact: true,
      kidTag: 'Leo',
    },
    {
      id: 403,
      name: 'Grandma Ellen & Grandpa Joe',
      category: 'family',
      relationship: 'Grandparents (Emergency Backup)',
      mobile: '+1 (555) 832-7744',
      landline: '+1 (555) 832-7700',
      email: 'ellen.grandma@gmail.com',
      address: '45 Magnolia Drive, Springfield (10 mins away)',
      notes: 'Has spare house key and car seats in the SUV.',
      isEmergencyContact: true,
      kidTag: 'Family / All',
    },
    {
      id: 404,
      name: 'Chloe Miller (CPR Certified)',
      category: 'carer',
      relationship: 'Trusted Weekend Babysitter',
      mobile: '+1 (555) 919-4820',
      email: 'chloe.m.babysitting@gmail.com',
      address: 'Maple St Apts #4B',
      notes: 'Available Friday/Saturday evenings and Sunday afternoons. Rate: $20/hr.',
      isEmergencyContact: false,
      kidTag: 'Family / All',
    },
    {
      id: 405,
      name: 'Dave’s Reliable Plumbing & HVAC',
      category: 'service',
      relationship: 'Emergency Home Maintenance',
      mobile: '+1 (555) 723-8899',
      landline: '+1 (555) 723-8800',
      email: 'service@davesplumbinghvac.com',
      address: '88 Industrial Blvd',
      notes: '24/7 emergency dispatch. Installed our new water heater in 2024.',
      isEmergencyContact: false,
    },
  ],
  recipes: [
    {
      id: 501,
      title: 'Sheet-Pan Lemon Herb Butter Chicken & Crispy Broccoli',
      sourceUrl: 'https://familyfoodmom.com/sheet-pan-lemon-chicken',
      prepTime: '15 mins',
      cookTime: '25 mins',
      baseServings: 4,
      currentServings: 4,
      mealType: 'dinner',
      tags: ['Kid-Friendly', 'One-Pot / Sheet Pan', 'Quick 20-Min'],
      isFavorite: true,
      isInShoppingList: true,
      notes: 'Kids love the crispy broccoli florets. Serve with garlic butter rice or warm pita bread.',
      ingredients: [
        { id: 'i1', name: 'Boneless Skinless Chicken Breasts (cubed)', baseAmount: 1.5, unit: 'lbs', department: 'Meat & Seafood' },
        { id: 'i2', name: 'Fresh Broccoli Florets', baseAmount: 3, unit: 'cups', department: 'Produce' },
        { id: 'i3', name: 'Olive Oil', baseAmount: 3, unit: 'tbsp', department: 'Pantry & Dry Goods' },
        { id: 'i4', name: 'Fresh Lemon Juice & Zest', baseAmount: 2, unit: 'tbsp', department: 'Produce' },
        { id: 'i5', name: 'Garlic Powder', baseAmount: 1, unit: 'tsp', department: 'Pantry & Dry Goods' },
        { id: 'i6', name: 'Dried Oregano & Thyme', baseAmount: 1, unit: 'tsp', department: 'Pantry & Dry Goods' },
        { id: 'i7', name: 'Grated Parmesan Cheese', baseAmount: 0.5, unit: 'cup', department: 'Dairy & Refrigerated' },
      ],
      instructions: [
        'Preheat oven to 400°F (200°C) and line a large baking sheet with parchment paper.',
        'In a large bowl, toss the cubed chicken and broccoli florets with olive oil, lemon juice, garlic powder, herbs, salt, and black pepper.',
        'Spread in a single even layer on the baking sheet.',
        'Roast for 20-25 minutes until chicken reaches 165°F and broccoli edges are golden-crisp.',
        'Sprinkle warm Parmesan cheese and fresh lemon zest immediately before serving.',
      ],
    },
    {
      id: 502,
      title: 'Mompreneur High-Protein Sunday Batch Bolognese',
      sourceUrl: 'https://nourishingmoms.com/batch-bolognese-pasta',
      prepTime: '20 mins',
      cookTime: '45 mins',
      baseServings: 6,
      currentServings: 6,
      mealType: 'dinner',
      tags: ['Meal Prep Batch', 'Kid-Friendly', 'Comfort Food'],
      isFavorite: true,
      isInShoppingList: false,
      notes: 'Great for freezing in silicone Souper Cubes for frantic weekday dinners.',
      ingredients: [
        { id: 'i8', name: 'Lean Ground Beef or Turkey', baseAmount: 2, unit: 'lbs', department: 'Meat & Seafood' },
        { id: 'i9', name: 'Diced Yellow Onion & Carrots (hidden veggies)', baseAmount: 2, unit: 'cups', department: 'Produce' },
        { id: 'i10', name: 'Crushed San Marzano Tomatoes', baseAmount: 28, unit: 'oz can', department: 'Pantry & Dry Goods' },
        { id: 'i11', name: 'Tomato Paste', baseAmount: 3, unit: 'tbsp', department: 'Pantry & Dry Goods' },
        { id: 'i12', name: 'Whole Milk or Heavy Cream', baseAmount: 0.5, unit: 'cup', department: 'Dairy & Refrigerated' },
        { id: 'i13', name: 'Rigatoni or Tagliatelle Pasta', baseAmount: 16, unit: 'oz box', department: 'Pantry & Dry Goods' },
        { id: 'i14', name: 'Minced Garlic Cloves', baseAmount: 4, unit: 'cloves', department: 'Produce' },
      ],
      instructions: [
        'Brown ground meat with onions and finely grated carrots in a heavy Dutch oven over medium heat until cooked through.',
        'Add minced garlic and tomato paste, stirring for 2 minutes until fragrant.',
        'Pour in crushed tomatoes and simmer on low for 35-40 minutes.',
        'Stir in whole milk/cream during the final 5 minutes for authentic silkiness.',
        'Boil pasta to al dente, toss with sauce, and garnish with fresh basil.',
      ],
    },
    {
      id: 503,
      title: 'Power-Morning Berry Chia Protein Overnight Oats',
      sourceUrl: '',
      prepTime: '10 mins',
      cookTime: '0 mins',
      baseServings: 4,
      currentServings: 4,
      mealType: 'breakfast',
      tags: ['Meal Prep Batch', 'Healthy & Fresh', 'Quick 20-Min'],
      isFavorite: false,
      isInShoppingList: true,
      notes: 'Make 4 mason jars on Sunday evening for grab-and-go school morning breakfasts.',
      ingredients: [
        { id: 'i15', name: 'Rolled Oats (Gluten-Free)', baseAmount: 2, unit: 'cups', department: 'Pantry & Dry Goods' },
        { id: 'i16', name: 'Chia Seeds', baseAmount: 4, unit: 'tbsp', department: 'Pantry & Dry Goods' },
        { id: 'i17', name: 'Almond Milk or Oat Milk', baseAmount: 2.5, unit: 'cups', department: 'Dairy & Refrigerated' },
        { id: 'i18', name: 'Greek Yogurt (Vanilla or Plain)', baseAmount: 1, unit: 'cup', department: 'Dairy & Refrigerated' },
        { id: 'i19', name: 'Pure Maple Syrup or Honey', baseAmount: 3, unit: 'tbsp', department: 'Pantry & Dry Goods' },
        { id: 'i20', name: 'Mixed Fresh or Frozen Berries', baseAmount: 1.5, unit: 'cups', department: 'Produce' },
      ],
      instructions: [
        'In a large mixing bowl or 4 mason jars, whisk rolled oats, chia seeds, and milk together.',
        'Fold in Greek yogurt and maple syrup until smoothly blended.',
        'Layer mixed berries on top and seal jars tightly.',
        'Refrigerate overnight (or minimum 4 hours). Keeps fresh for up to 5 days.',
      ],
    },
  ],
  shoppingList: [
    { id: 's1', name: 'Boneless Skinless Chicken Breasts', amount: '1.5 lbs', department: 'Meat & Seafood', checked: false, recipeSource: 'Sheet-Pan Lemon Herb Chicken', recipeId: 501, isAutoGenerated: true },
    { id: 's2', name: 'Fresh Broccoli Florets', amount: '3 cups', department: 'Produce', checked: false, recipeSource: 'Sheet-Pan Lemon Herb Chicken', recipeId: 501, isAutoGenerated: true },
    { id: 's3', name: 'Fresh Lemons & Zest', amount: '2 tbsp', department: 'Produce', checked: true, recipeSource: 'Sheet-Pan Lemon Herb Chicken', recipeId: 501, isAutoGenerated: true },
    { id: 's4', name: 'Grated Parmesan Cheese', amount: '0.5 cup', department: 'Dairy & Refrigerated', checked: false, recipeSource: 'Sheet-Pan Lemon Herb Chicken', recipeId: 501, isAutoGenerated: true },
    { id: 's5', name: 'Rolled Oats (Gluten-Free)', amount: '2 cups', department: 'Pantry & Dry Goods', checked: false, recipeSource: 'Power-Morning Overnight Oats', recipeId: 503, isAutoGenerated: true },
    { id: 's6', name: 'Greek Yogurt (Vanilla or Plain)', amount: '1 cup', department: 'Dairy & Refrigerated', checked: false, recipeSource: 'Power-Morning Overnight Oats', recipeId: 503, isAutoGenerated: true },
    { id: 's7', name: 'Kid Lunchbox Snacks & Apples', amount: '1 bag', department: 'Produce', checked: true },
  ],
  schedule: [
    {
      id: 1,
      text: 'School Drop-off & Gymnastics Bag',
      date: getTodayDateString(),
      time: '07:45',
      mode: 'family',
      completed: true,
      location: 'Oakridge Elementary (Gate B)',
      assignee: 'Mom',
      recurrence: {
        frequency: 'daily',
        label: 'Repeats Mon-Fri',
      },
      prepList: [
        { id: 'p1', text: 'Pack gymnastics leotard & water bottle', done: true },
        { id: 'p2', text: 'Sign permission slip for science museum', done: true },
        { id: 'p3', text: 'Handover afternoon pickup note to Mrs. Vance', done: false },
      ],
    },
    {
      id: 2,
      text: 'Pediatric Dental Checkup - Maya',
      date: getTodayDateString(),
      time: '15:30',
      mode: 'family',
      completed: false,
      location: 'Bright Smiles Pediatric Dental, Suite 200',
      assignee: 'Dad',
      recurrence: {
        frequency: 'monthly',
        dayOfMonth: 14,
        label: 'Monthly Check-in',
      },
      prepList: [
        { id: 'p4', text: 'Bring insurance dental card', done: false },
        { id: 'p5', text: 'Bring favorite toy for waiting room', done: true },
      ],
    },
    {
      id: 3,
      text: 'Client Strategy Review & Pitch Call',
      date: getTodayDateString(),
      time: '09:30',
      mode: 'business',
      completed: false,
      assignee: 'Mom',
      recurrence: {
        frequency: 'weekly',
        dayOfWeek: 2,
        dayOfWeekName: 'Tuesday',
        label: 'Weekly on Tuesdays',
      },
    },
    {
      id: 4,
      text: 'Social Media Reel & Story Recording',
      date: getTodayDateString(),
      time: '11:30',
      mode: 'marketing',
      completed: false,
      recurrence: {
        frequency: 'weekly',
        dayOfWeek: 4,
        dayOfWeekName: 'Thursday',
        label: 'Weekly on Thursdays',
      },
    },
    {
      id: 5,
      text: 'Afternoon Mindful Walk & Hydrate',
      date: getTodayDateString(),
      time: '14:00',
      mode: 'self',
      completed: false,
      recurrence: {
        frequency: 'daily',
        label: 'Daily Habit',
      },
    },
    {
      id: 6,
      text: 'Operations & Invoicing Sprint',
      date: getTodayDateString(),
      time: '15:00',
      mode: 'business',
      completed: false,
      location: 'Executive Desk / Accounting Portal',
      assignee: 'Mom',
      recurrence: {
        frequency: 'weekly',
        dayOfWeek: 5,
        dayOfWeekName: 'Friday',
        label: 'Weekly on Fridays',
      },
      prepList: [
        { id: 'p6', text: 'Reconcile weekly client deliverables', done: true },
        { id: 'p7', text: 'Send monthly retainer statements', done: false },
      ],
    },
    {
      id: 7,
      text: 'Deep Work Sprint: Strategy & Pipeline',
      date: getTodayDateString(),
      time: '16:30',
      mode: 'business',
      completed: false,
      recurrence: {
        frequency: 'daily',
        label: 'Daily Focus Block',
      },
    },
  ],
  priorities: [
    {
      id: 101,
      text: 'Finalize quarterly client proposals',
      done: false,
      mode: 'business',
      duration: '45 mins',
      delegation: 'myself',
      subTasks: [
        { id: 's1', text: 'Review scope deliverables with partner', done: true },
        { id: 's2', text: 'Attach pricing tier breakdown table', done: false },
        { id: 's3', text: 'Send PDF copy via email', done: false },
      ],
    },
    {
      id: 102,
      text: 'Science fair volcano project materials',
      done: false,
      mode: 'family',
      duration: '15 mins',
      delegation: 'needs_partner',
      subTasks: [
        { id: 's4', text: 'Check pantry for vinegar & baking soda', done: true },
        { id: 's5', text: 'Have partner pick up red craft dye & clay', done: false },
      ],
    },
    {
      id: 103,
      text: 'Confirm Leo soccer carpool schedule',
      done: true,
      mode: 'family',
      duration: '5 mins',
      delegation: 'delegated_partner',
    },
    {
      id: 104,
      text: 'Record 2 reels for product launch',
      done: false,
      mode: 'marketing',
      duration: '30 mins',
      delegation: 'myself',
      subTasks: [
        { id: 's6', text: 'Set up ring light in kitchen nook', done: false },
        { id: 's7', text: 'Film 30-second workflow demo', done: false },
      ],
    },
  ],
  notes: [
    {
      id: 201,
      text: 'Leo science fair project checklist: Vinegar, food coloring, poster board. Project due next Friday!',
      mode: 'family',
      createdAt: 'Today, 8:15 AM',
      pinned: true,
      kidTag: 'Leo',
      hasAudioMemo: true,
      audioDuration: '0:38',
    },
    {
      id: 202,
      text: 'Maya ballet recital dress rehearsal schedule: Saturday 10:00 AM at the civic auditorium. Hair in high bun.',
      mode: 'family',
      createdAt: 'Yesterday, 4:20 PM',
      pinned: false,
      kidTag: 'Maya',
    },
    {
      id: 203,
      text: 'Test new discount coupon code "MOMPOWER20" on checkout flow before Friday email blast.',
      mode: 'marketing',
      createdAt: 'Today, 10:30 AM',
      pinned: false,
    },
    {
      id: 204,
      text: 'Client contract deliverable: Update SLA terms for Q4 onboarding retainers and invoice by Wednesday.',
      mode: 'business',
      createdAt: 'Today, 9:00 AM',
      pinned: true,
    },
    {
      id: 205,
      text: 'Content strategy idea: "Automating Admin Friction and Time-Blocking for Deep Focus".',
      mode: 'marketing',
      createdAt: 'Yesterday, 2:15 PM',
      pinned: false,
    },
  ],
  expenses: [
    {
      id: 301,
      text: 'Kids School Stationery & Science Supplies',
      amount: 24.5,
      currency: 'USD',
      mode: 'family',
      date: getTodayDateString(),
      subCategory: 'School Supplies',
      kidTag: 'Leo',
      reimbursementStatus: 'pending_split',
    },
    {
      id: 302,
      text: 'Pediatric Dental Co-pay - Maya',
      amount: 45.0,
      currency: 'USD',
      mode: 'family',
      date: getTodayDateString(),
      subCategory: 'Medical & Pharmacy',
      kidTag: 'Maya',
      reimbursementStatus: 'reimbursed',
    },
    {
      id: 303,
      text: 'Email Marketing Platform Subscription',
      amount: 29.0,
      currency: 'USD',
      mode: 'business',
      date: getTodayDateString(),
      subCategory: 'Software & Apps',
      reimbursementStatus: 'claimable',
    },
  ],
};

