export type ContextMode = 'family' | 'business' | 'marketing' | 'self';

export type CurrencyCode = 'ZAR' | 'USD' | 'EUR' | 'GBP' | 'CAD' | 'AUD';

export type FullPageView =
  | 'none'
  | 'schedule'
  | 'braindump'
  | 'priorities'
  | 'expenses'
  | 'contacts'
  | 'recipes';

export type ScheduleViewMode = 'day' | 'week' | 'month' | 'year';

export type PriorityColumn = 'today' | 'this_week' | 'backlog';

export type RecurrenceFrequency = 'none' | 'daily' | 'weekly' | 'monthly';

export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  dayOfWeek?: number; // 0 = Sun, 1 = Mon, 2 = Tue, etc.
  dayOfWeekName?: string; // e.g. "Tuesday"
  dayOfMonth?: number; // 1-31
  label?: string; // e.g. "Daily", "Weekly on Tuesdays", "Monthly on the 1st"
}

export interface PrepItem {
  id: string;
  text: string;
  done: boolean;
}

export type Assignee = 'Mom' | 'Dad' | 'Partner' | 'Carers' | 'Kids' | 'Both' | string;

export interface ScheduleItem {
  id: number;
  text: string;
  date: string;
  time: string;
  mode: ContextMode;
  completed?: boolean;
  // Family & Detailed fields
  location?: string;
  mapLink?: string;
  prepList?: PrepItem[];
  assignee?: Assignee;
  recurrence?: RecurrenceRule;
}

export interface PrioritySubTask {
  id: string;
  text: string;
  done: boolean;
}

export type DelegationStatus =
  | 'myself'
  | 'needs_partner'
  | 'needs_kid'
  | 'delegated_partner'
  | 'delegated_kid';

export interface PriorityItem {
  id: number;
  text: string;
  done: boolean;
  mode?: ContextMode;
  column?: PriorityColumn;
  // Detailed fields
  duration?: string; // e.g. "15 mins", "30 mins", "1 hour"
  delegation?: DelegationStatus;
  subTasks?: PrioritySubTask[];
  recurrence?: RecurrenceRule;
  completedAt?: string;
  tags?: string[];
  kidTag?: string;
  category?: string;
}

export interface NoteItem {
  id: number;
  text: string;
  mode: ContextMode;
  createdAt?: string;
  pinned?: boolean;
  // Detailed fields
  kidTag?: string; // e.g. "Leo", "Maya", "All Kids", "General"
  imageUrl?: string; // base64 data URL or photo url
  imageName?: string;
  hasAudioMemo?: boolean;
  audioDuration?: string;
}

export type ReimbursementStatus = 'none' | 'pending_split' | 'reimbursed' | 'claimable';

export interface ExpenseItem {
  id: number;
  text: string;
  amount: number;
  currency?: string;
  mode?: ContextMode;
  date?: string;
  // Detailed fields
  subCategory?: string; // e.g. "School Supplies", "Extracurriculars", "Medical", "Clothing"
  kidTag?: string; // e.g. "Leo", "Maya", "Family"
  receiptImage?: string; // base64 data URL
  reimbursementStatus?: ReimbursementStatus;
  tags?: string[];
  category?: string;
}

export type ContactCategory =
  | 'emergency'
  | 'family'
  | 'medical'
  | 'school'
  | 'carer'
  | 'service'
  | 'business'
  | 'other';

export interface ContactItem {
  id: number;
  name: string;
  category: ContactCategory;
  relationship?: string; // e.g. "Pediatrician", "Grade 2 Teacher", "Babysitter", "Plumber"
  mobile?: string;
  landline?: string;
  email?: string;
  address?: string;
  notes?: string;
  isEmergencyContact?: boolean;
  kidTag?: string;
  tags?: string[];
}

export type GroceryDepartment =
  | 'Produce'
  | 'Dairy & Refrigerated'
  | 'Meat & Seafood'
  | 'Pantry & Dry Goods'
  | 'Bakery & Snacks'
  | 'Other';

export interface RecipeIngredient {
  id: string;
  name: string;
  baseAmount: number; // For baseServings
  unit: string; // e.g. "cup", "tbsp", "tsp", "g", "oz", "lbs", "cloves", "whole"
  department: GroceryDepartment;
  notes?: string;
}

export interface RecipeItem {
  id: number;
  title: string;
  sourceUrl?: string;
  imageUrl?: string;
  prepTime?: string;
  cookTime?: string;
  baseServings: number;
  currentServings?: number;
  tags: string[];
  mealType?: 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'baking';
  ingredients: RecipeIngredient[];
  instructions: string[];
  notes?: string;
  isFavorite?: boolean;
  isInShoppingList?: boolean;
}

export interface ShoppingListItem {
  id: string;
  name: string;
  amount?: string;
  department: GroceryDepartment;
  checked: boolean;
  recipeSource?: string;
  recipeId?: number;
  isAutoGenerated?: boolean;
}

export interface MomOsState {
  customQuickAdds: Record<ContextMode, string[]>;
  schedule: ScheduleItem[];
  priorities: PriorityItem[];
  notes: NoteItem[];
  expenses: ExpenseItem[];
  kidTags?: string[];
  contacts: ContactItem[];
  recipes: RecipeItem[];
  shoppingList: ShoppingListItem[];
}

export interface ModeConfig {
  id: ContextMode;
  title: string;
  shortTitle: string;
  scheduleTitle: string;
  iconName: string;
  defaultQuickAdds: string[];
  tagClass: string;
  badgeBg: string;
  badgeText: string;
  activeBtnBg: string;
  cardBorder: string;
  cardBg: string;
  accentText: string;
}


